library(tidyverse)
library(readxl)
library(patchwork)

setwd("/Users/mkh/GitHub/mor_dms_analysis/trupath_vs_camp_efficacy")

# ── Latest fit-derived values ───────────────────────────────────────────────────
# camp_trupath_scatter_values.csv is generated by compute_scatter_values.py, which
# fits both assays the same span-based / Hill=1 way as the DRC figures:
#   cAMP    from transcriptional_drc.xlsx
#   TruPath from the raw pzfx (MP -4 outlier dropped)
# Emax = (Bottom-Top)/DAMGO_span*100 ; EC50 = fitted LogEC50.
vals <- read_csv("camp_trupath_scatter_values.csv", show_col_types = FALSE)
eff  <- vals %>% filter(!is.na(camp_pct),  !is.na(trupath_pct))
ec50 <- vals %>% filter(!is.na(camp_ec50), !is.na(trupath_ec50))

# ── Shared styling ─────────────────────────────────────────────────────────────
lw <- 0.5 / 2.835

txt <- element_text(color = "black", size = 6, face = "plain", family = "Helvetica")

base_theme <- theme_classic(base_size = 6, base_family = "Helvetica") +
  theme(
    text              = txt,
    axis.text         = txt,
    axis.text.x       = txt,
    axis.text.y       = txt,
    axis.title        = txt,
    axis.title.x      = txt,
    axis.title.y      = txt,
    axis.line         = element_line(color = "black", linewidth = lw),
    axis.ticks        = element_line(color = "black", linewidth = lw),
    plot.title        = element_text(color = "black", size = 6, face = "plain", family = "Helvetica", hjust = 0.5),
    plot.background   = element_rect(fill = NA, color = NA),
    panel.background  = element_rect(fill = NA, color = NA),
    plot.margin       = margin(0, 1, 0, 1),
    legend.position   = "none"
  )

# ── Efficacy panel ─────────────────────────────────────────────────────────────
rho_eff <- cor(eff$camp_pct, eff$trupath_pct, method = "spearman")
lab_eff <- sprintf("rho == %.2f", rho_eff)

p_eff <- ggplot(eff, aes(x = trupath_pct, y = camp_pct)) +
  geom_abline(slope = 1, intercept = 0,
              color = "grey70", linewidth = lw, linetype = "dashed") +
  geom_point(shape = 16, size = 1.0, alpha = 0.95, color = "black") +
  annotate("text", x = Inf, y = -Inf, label = lab_eff, parse = TRUE,
           family = "Helvetica",
           hjust = 1.1, vjust = -0.8, size = 6 / .pt, color = "black") +
  scale_x_continuous(limits = c(0, 105), expand = c(0, 0),
                     breaks = c(0, 25, 50, 75, 100),
                     labels = function(x) ifelse(x %in% c(25, 75), "", as.character(x))) +
  scale_y_continuous(limits = c(0, 105), expand = c(0, 0),
                     breaks = c(0, 25, 50, 75, 100),
                     labels = function(x) ifelse(x %in% c(25, 75), "", as.character(x))) +
  coord_cartesian(clip = "off") +
  labs(title = expression(E[max]*", % DAMGO"), x = NULL, y = "Pooled cAMP") +
  base_theme +
  theme(axis.title.x = element_blank())

# ── EC50 panel ─────────────────────────────────────────────────────────────────
rho_ec50 <- cor(ec50$camp_ec50, ec50$trupath_ec50, method = "spearman")
lab_ec50 <- sprintf("rho == %.2f", rho_ec50)

p_ec50 <- ggplot(ec50, aes(x = trupath_ec50, y = camp_ec50)) +
  geom_abline(slope = 1, intercept = 0,
              color = "grey70", linewidth = lw, linetype = "dashed") +
  geom_point(shape = 16, size = 1.0, alpha = 0.95, color = "black") +
  annotate("text", x = Inf, y = -Inf, label = lab_ec50, parse = TRUE,
           family = "Helvetica",
           hjust = 1.1, vjust = -0.8, size = 6 / .pt, color = "black") +
  scale_x_continuous(limits = c(-13, -5), expand = c(0, 0),
                     breaks = seq(-12, -6, by = 1),
                     labels = function(x) ifelse(x %% 2 == 0, as.character(x), "")) +
  scale_y_continuous(limits = c(-13, -5), expand = c(0, 0),
                     breaks = seq(-12, -6, by = 1),
                     labels = function(x) ifelse(x %% 2 == 0, as.character(x), "")) +
  coord_cartesian(clip = "off") +
  labs(title = expression(EC[50]*", log[ligand]"), x = NULL, y = NULL) +
  base_theme +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank())

# ── Compose: two panels side-by-side, shared x-axis caption, no legend ──────────
plots_only <- (p_eff + p_ec50) +
  plot_annotation(
    caption = "TRUPATH Gi1",
    theme = theme(
      plot.caption = element_text(color = "black", size = 6, family = "Helvetica",
                                  face = "plain", hjust = 0.5,
                                  margin = margin(t = 1, b = 0)),
      plot.margin = margin(0.5, 1.9, 0.5, 1.9, unit = "mm")
    )
  )

ggsave("camp_vs_trupath_plots_black.pdf", plots_only,
       width = 57.5, height = 35.4, units = "mm",
       bg = "transparent")
message("Saved: ", file.path(getwd(), "camp_vs_trupath_plots_black.pdf"))
