#!/usr/bin/env python3
"""
Per-position PC score reference table.

For every position (65-355) collects:
  - averaged VARIANT-level PC1-3 (mean over that position's missense variants;
    variant PCA is sign-aligned to the position PCA) -> what you'd paint on the
    structure to keep panel g on the variant PCA
  - straight POSITION-level PC1-3 (position PCA) for side-by-side reference

Output: plots/pca/per_position_pc_scores.xlsx  (+ .csv fallback)
"""
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "plots" / "pca"

# variant scores -> per-position mean
var = pd.read_csv(OUT / "variant" / "pca_variant_scores.csv")
vagg = (var.groupby("position")
           .agg(wildtype=("wildtype", "first"),
                n_variants=("PC2", "size"),
                variant_PC1=("PC1", "mean"),
                variant_PC2=("PC2", "mean"),
                variant_PC3=("PC3", "mean"))
           .reset_index())

# position scores (+ SSE region annotation, already merged in pca_position_scores.csv)
pos = pd.read_csv(OUT / "position" / "pca_position_scores.csv")
pos_cols = ["position", "PC1", "PC2", "PC3"] + (["SSE"] if "SSE" in pos.columns else [])
pos = pos[pos_cols].rename(columns={"PC1": "position_PC1",
                                     "PC2": "position_PC2",
                                     "PC3": "position_PC3",
                                     "SSE": "region"})

tbl = (vagg.merge(pos, on="position", how="outer")
           .sort_values("position")
           .reset_index(drop=True))
tbl["position"] = tbl["position"].astype("Int64")

# tidy column order
order = ["position", "wildtype"] + (["region"] if "region" in tbl.columns else []) + \
        ["n_variants", "variant_PC1", "variant_PC2", "variant_PC3",
         "position_PC1", "position_PC2", "position_PC3"]
tbl = tbl[order]
for c in tbl.columns:
    if tbl[c].dtype.kind == "f":
        tbl[c] = tbl[c].round(4)

notes = pd.DataFrame({"README": [
    "Per-position PC scores for the mu-opioid receptor DMS PCAs.",
    "",
    "variant_PCx  = mean over all missense variants at that position of the",
    "               VARIANT-level PCA scores (rows = variants). Signs aligned to",
    "               the position PCA. Use these to paint panel g on the variant PCA.",
    "position_PCx = POSITION-level PCA scores (rows = per-position mean effects).",
    "",
    "PC2 (efficacy axis): variant_PC2 vs position_PC2 correlate at r = 0.997.",
    "Variance explained  -  variant PCA: PC1 49.1%, PC2 10.2%",
    "                       position PCA: PC1 66.8%, PC2 15.6%",
    "n_variants   = number of missense variants averaged at that position.",
    "region       = GPCRdb secondary-structure element (TM1-7, ICL, ECL, H8).",
    "",
    "Generated by plots/pca/build_per_position_pc_table.py",
]})

try:
    with pd.ExcelWriter(OUT / "per_position_pc_scores.xlsx", engine="openpyxl") as xw:
        tbl.to_excel(xw, sheet_name="per_position_PC", index=False)
        notes.to_excel(xw, sheet_name="notes", index=False)
    print(f"Wrote {OUT/'per_position_pc_scores.xlsx'}  ({len(tbl)} positions)")
except ImportError:
    tbl.to_csv(OUT / "per_position_pc_scores.csv", index=False)
    print(f"openpyxl missing -> wrote CSV instead: {OUT/'per_position_pc_scores.csv'} ({len(tbl)} positions)")

# always write a csv too for portability
tbl.to_csv(OUT / "per_position_pc_scores.csv", index=False)
print(tbl.head(8).to_string(index=False))
